[project]
name = "sakuragasaki46_suou"
authors = [
    { name = "Sakuragasaki46" }
]
dynamic = [ "version" ]
dependencies = [
    "itsdangerous",
    "toml"
]
requires-python = ">=3.10"
license = "Apache-2.0"
readme = "README.md"

# - publishing -
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    
    # actively supported Pythons
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

[project.urls]
Repository = "https://github.com/sakuragasaki46/suou"

[project.optional-dependencies]
sqlalchemy = [
    "SQLAlchemy>=2.0.0"
]
flask = [
    "Flask>=2.0.0",
    "Flask-RestX"
]
peewee = [
    "peewee>=3.0.0, <4.0"
]


[tool.setuptools.dynamic]
version = { attr = "suou.__version__" }
